### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by citrux** [dead-pine-inc/book-of-the-idea-out#7]
Есть идеи как подключить тревис к этому репозиторию, чтобы проверять косяки без сборки на своей машине? Там ему придётся много чего ставить -- texlive-fonts-extra немало весят.

**Comment by FreeCX** [comment]
@citrux, возможно что-то типа этого https://harshjv.github.io/blog/setup-latex-pdf-build-using-travis-ci/
